version: "3.7"

services:
    php:
        build:
            context: .docker
            dockerfile: Dockerfile
        ports:
            - "${PHPSERBIA_HTTPD_PORT:-80}:80"
        depends_on:
            - db
        volumes:
            - ./:/var/www/symfony:cached
            - ./.docker/default.conf:/etc/apache2/sites-available/000-default.conf:ro

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: demo
            MYSQL_USER: demo
            MYSQL_PASSWORD: demo
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - ./.docker/db:/docker-entrypoint-initdb.d:ro
        command:
            - "--default-authentication-plugin=mysql_native_password"

    db2:
        image: mysql:8
        environment:
            MYSQL_DATABASE: demo2
            MYSQL_USER: demo2
            MYSQL_PASSWORD: demo2
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        volumes:
            - ./.docker/db2:/docker-entrypoint-initdb.d:ro
        command:
            - "--default-authentication-plugin=mysql_native_password"

    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
            - "${PHPSERBIA_MAILHOG_PORT:-8025}:8025"
