invoice_new:
    methods: GET|POST
    path: /invoice/new
    controller: App\UI\Action\Invoice\Create::handle

invoice_delete:
    methods: DELETE
    path: /invoice/{id}
    controller: App\UI\Action\Invoice\Delete::handle

invoice_edit:
    methods: GET|POST
    path: /invoice/{id}/edit
    controller: App\UI\Action\Invoice\Edit::handle

invoice_index:
    methods: GET
    path: /invoice
    controller: App\UI\Action\Invoice\Listing::handle

invoice_show:
    methods: GET
    path: /invoice/{id}
    controller: App\UI\Action\Invoice\Show::handle
